/**
 * Materialize the harness runtime the application embeds.
 *
 * The product ships a self-contained backend: `Resources/backend` is an
 * ordinary `node_modules` tree the Electron binary runs `@deepseek-ai/dsh`'s
 * `lib/bin.js` out of, with no package manager, Node installation, or checkout
 * on the target machine. This module is what produces that tree.
 *
 * It installs OUTSIDE this repository's workspace, and deliberately so. The
 * staging directory is given a `pnpm-workspace.yaml` of its own declaring
 * `packages: []`, which makes it a workspace root with no members: pnpm stops
 * walking up, the desktop workspace's catalog and lockfile never apply, and the
 * closure resolves purely from the registry. That is the same reason
 * `runtime/package.json` restates the harness version literally instead of
 * naming a catalog entry — see this repository's `pnpm-workspace.yaml`, and
 * `pnpm run check:harness-pin`, which proves the two agree.
 *
 * The tree is installed with the hoisted node linker, because it has to survive
 * being copied into an `.app` bundle: pnpm's default layout is a symlink farm
 * pointing into a store that will not be there.
 * @module @omdsh-plugins/omdsh-desktop/scripts/runtime-closure
 */

import { mkdir, rm, writeFile } from 'node:fs/promises'
import { join, resolve, sep } from 'node:path'
import { runCommand } from './run-command.ts'

/** The closure's command directory, relative to its root. */
export const CLOSURE_BIN_RELATIVE = join('node_modules', '.bin')

/** The pnpm launcher inside the closure, relative to {@link CLOSURE_BIN_RELATIVE}. */
const PNPM_ENTRY_FROM_BIN = '..\\pnpm\\bin\\pnpm.mjs'

/**
 * The application executable, relative to {@link CLOSURE_BIN_RELATIVE}.
 *
 * Four levels: `.bin` → `node_modules` → `backend` → `Resources` → the
 * directory `electron-builder` puts the executable in. Fixed by that layout
 * rather than discovered, because the shim is written into the staged closure
 * before the closure is copied into it.
 */
const LAUNCHER_FROM_BIN = '..\\..\\..\\..'

/**
 * The Windows command shim that makes the shipped pnpm runnable.
 *
 * ## Why a closure built on macOS needs one written by hand
 *
 * pnpm creates a `.bin` entry per platform it installs ON, not per platform it
 * installs FOR: a Windows closure cross-built from macOS gets POSIX symlinks
 * (`pnpm -> ../pnpm/bin/pnpm.mjs`) and no `.cmd` at all. Windows cannot execute
 * one — there is no extension for `PATHEXT` to match and the target is a script
 * — and `omdsh-plughub` will not even look at it: its search asks for
 * `pnpm.cmd`, `pnpm.exe`, or `pnpm.bat` on `win32`.
 *
 * The consequence is narrow and total. `dsh plugin` spawns `pnpm` by bare name;
 * the hub answers the question `PATH` cannot by putting the directory holding a
 * pnpm in front of the child's. With no `.cmd` there, that search falls through
 * to the directories pnpm's own installers use, finds nothing on a machine that
 * has never had pnpm, and every Install button in the hub fails with `pnpm not
 * found on PATH` — on the exact machine the installer was built to serve.
 *
 * ## Why it calls the application rather than `node`
 *
 * The bundle ships no `node.exe`. The runtime is the application's own Electron
 * binary run with `ELECTRON_RUN_AS_NODE`, which is the whole reason the bundle
 * carries one Node and not two, so the shim reaches for the same binary the
 * same way.
 *
 * Nothing else is shimmed, deliberately. A `node.cmd` beside this one would go
 * in front of the child's `PATH` too, and then a plugin whose `prepare` runs a
 * native toolchain (`tsdown` loads a Rolldown `.node` binding built for Node's
 * ABI, not Electron's) would fail to load it instead of failing to find Node —
 * the same outcome, reported worse. A registry install runs no build at all,
 * which is what this shim is for.
 * @param executableName - the application executable's filename, extension included.
 * @returns the shim, CRLF-terminated as a batch file should be.
 */
export function windowsPnpmShim(executableName: string): string {
  return [
    '@ECHO off',
    'REM Generated by scripts/runtime-closure.ts. A closure cross-built from macOS',
    'REM carries POSIX symlinks in .bin and no .cmd, which Windows cannot run and',
    'REM omdsh-plughub does not look for. This is the shipped pnpm, reached through',
    'REM the application binary because the bundle ships no node.exe.',
    'SETLOCAL',
    'SET "ELECTRON_RUN_AS_NODE=1"',
    `"%~dp0${LAUNCHER_FROM_BIN}\\${executableName}" "%~dp0${PNPM_ENTRY_FROM_BIN}" %*`,
    'ENDLOCAL & EXIT /B %ERRORLEVEL%',
    '',
  ].join('\r\n')
}

/**
 * Write the Windows pnpm shim into a staged closure.
 * @param options - the closure and the executable to reach.
 * @param options.staging - the deployed closure.
 * @param options.executableName - the application executable's filename.
 * @param options.prefix - diagnostic prefix.
 * @param options.dryRun - report what would happen and change nothing.
 * @returns nothing; the shim is on disk beside the closure's other commands.
 */
export async function writeWindowsPnpmShim(options: {
  staging: string
  executableName: string
  prefix: string
  dryRun: boolean
}): Promise<void> {
  const path = join(options.staging, CLOSURE_BIN_RELATIVE, 'pnpm.cmd')
  if (options.dryRun) {
    console.log(`${options.prefix}: would write the Windows pnpm shim at ${path}`)
    return
  }
  await mkdir(join(options.staging, CLOSURE_BIN_RELATIVE), { recursive: true })
  await writeFile(path, windowsPnpmShim(options.executableName))
  console.log(`${options.prefix}: wrote the Windows pnpm shim, which the plugin hub installs through`)
}

/** Name of the synthesized deploy root. It is private and never published. */
const CLOSURE_NAME = 'omdsh-runtime-closure'

/** Version of the synthesized deploy root. Nothing reads it; pnpm requires one. */
const CLOSURE_VERSION = '0.0.1'

/**
 * Which dependencies of the closure may run an install script.
 *
 * pnpm 10+ blocks every install and build script until it is reviewed, and the
 * staging root gets no say from this repository's own `pnpm-workspace.yaml` —
 * it is a separate workspace by construction. So the review travels here.
 *
 * Narrower than the desktop workspace's list, because this is the RUNTIME's
 * closure rather than the shell's: `electron` and `esbuild` are the shell's
 * build-time dependencies and never appear here. `node-addon-require-builtin`
 * reaches the closure but is left unlisted, which denies it, exactly as the
 * workspace denies it.
 */
const CLOSURE_ALLOW_BUILDS: Readonly<Record<string, boolean>> = {
  // Restores the executable bit on the macOS spawn helper, which the
  // persistent-terminal tools need in the shipped closure.
  '@deepseek-ai/dsh-subprocess-local': true,
  // JSONL durability calls MoveFileExW with write-through publication on Windows.
  koffi: true,
  // The persistent PTY backend, including ConPTY on Windows.
  'node-pty': true,
  // Pulled in by an optional LLM API backend; its lifecycle scripts are no-ops
  // the runtime does not need.
  '@google/genai': false,
  protobufjs: false,
}

/** What a closure install needs to know. */
export interface InstallRuntimeClosureOptions {
  /** Directory to materialize the closure in. Replaced wholesale. */
  readonly staging: string
  /** The dependency map to install, as the runtime pin records it. */
  readonly dependencies: Readonly<Record<string, string>>
  /** pnpm settings the staged install must carry, when the pin sets any. */
  readonly pnpm?: Readonly<Record<string, unknown>>
  /** Directory the install must never write into or delete: the repository. */
  readonly protect: string
  /** Diagnostic prefix on this step's logs and errors. */
  readonly prefix: string
  /** Report what would happen and change nothing. */
  readonly dryRun: boolean
}

/**
 * The staging root's workspace file.
 *
 * Written as text rather than through a YAML serializer: this repository has no
 * YAML dependency, the document is three fixed keys, and every value in it is
 * either a boolean or a quoted package name.
 * @param allowBuilds - the reviewed build-script decisions.
 * @returns the document.
 */
function workspaceDocument(allowBuilds: Readonly<Record<string, boolean>>): string {
  const entries = Object.entries(allowBuilds)
    .map(([name, allowed]) => `  '${name}': ${String(allowed)}`)
    .join('\n')
  return [
    '# Generated by scripts/runtime-closure.ts. `packages: []` is what makes this',
    '# directory a workspace root of its own, so the install resolves from the',
    '# registry rather than through the desktop workspace above it.',
    'packages: []',
    'allowBuilds:',
    entries,
    '# Every dependency here is pinned to one release this repository chooses',
    "# deliberately, so pnpm's release-age gate has nothing left to protect.",
    'minimumReleaseAge: 0',
    '',
  ].join('\n')
}

/**
 * Refuse a staging directory that would take the repository with it.
 *
 * The install replaces `staging` wholesale, so a path that contains the
 * repository — or is it — turns one packaging run into data loss.
 * @param staging - the directory about to be replaced.
 * @param protect - the directory that must survive.
 * @param prefix - diagnostic prefix.
 * @throws Error when the staging directory is unsafe.
 */
function assertSafeStaging(staging: string, protect: string, prefix: string): void {
  const target = resolve(staging)
  const guarded = resolve(protect)
  if (target === guarded || guarded.startsWith(`${target}${sep}`)) {
    throw new Error(`${prefix}: refusing to stage the closure at ${target}, which contains ${guarded}.`)
  }
}

/**
 * Install the harness closure into the staging directory.
 * @param options - where to put it and what to put there.
 * @returns nothing; the closure is on disk at `options.staging`.
 * @throws Error when the staging directory is unsafe or the install fails.
 */
export async function installRuntimeClosure(options: InstallRuntimeClosureOptions): Promise<void> {
  assertSafeStaging(options.staging, options.protect, options.prefix)

  const manifest = {
    name: CLOSURE_NAME,
    version: CLOSURE_VERSION,
    private: true,
    type: 'module',
    dependencies: options.dependencies,
    ...options.pnpm !== undefined && { pnpm: options.pnpm },
  }

  if (options.dryRun) {
    console.log(`${options.prefix}: would stage the closure at ${options.staging}`)
    for (const [name, range] of Object.entries(options.dependencies)) {
      console.log(`${options.prefix}:   ${name}@${range}`)
    }
    return
  }

  // Replaced rather than updated: a closure carrying a previous run's pruned
  // tree, or a previous target's natives, is not the closure this pin names.
  await rm(options.staging, { recursive: true, force: true })
  await mkdir(options.staging, { recursive: true })
  await writeFile(join(options.staging, 'package.json'), `${JSON.stringify(manifest, undefined, 2)}\n`)
  await writeFile(join(options.staging, 'pnpm-workspace.yaml'), workspaceDocument(CLOSURE_ALLOW_BUILDS))

  await runCommand({
    label: 'deploy the harness closure',
    command: 'pnpm',
    // `--prod` because the closure runs the harness rather than building it,
    // and `--node-linker=hoisted` because the tree is about to be copied into
    // an application bundle, where a symlink into pnpm's store resolves to
    // nothing.
    args: ['install', '--prod', '--node-linker=hoisted'],
    cwd: options.staging,
    prefix: options.prefix,
    dryRun: false,
  })
}
