/**
 * Materialize the harness runtime the application embeds.
 *
 * The product ships a self-contained backend: `Resources/backend` is an
 * ordinary `node_modules` tree the Electron binary runs `@deepseek-ai/dsh`'s
 * `lib/bin.js` out of, with no package manager, Node installation, or checkout
 * on the target machine. This module is what produces that tree.
 *
 * It installs OUTSIDE this repository's workspace, and deliberately so. The
 * staging directory is given a `pnpm-workspace.yaml` of its own declaring
 * `packages: []`, which makes it a workspace root with no members: pnpm stops
 * walking up, the desktop workspace's catalog and lockfile never apply, and the
 * closure resolves purely from the registry. That is the same reason
 * `runtime/package.json` restates the harness version literally instead of
 * naming a catalog entry — see this repository's `pnpm-workspace.yaml`, and
 * `pnpm run check:harness-pin`, which proves the two agree.
 *
 * The tree is installed with the hoisted node linker, because it has to survive
 * being copied into an `.app` bundle: pnpm's default layout is a symlink farm
 * pointing into a store that will not be there.
 * @module @omdsh-plugins/omdsh-desktop/scripts/runtime-closure
 */

import { mkdir, rm, writeFile } from 'node:fs/promises'
import { join, resolve, sep } from 'node:path'
import { runCommand } from './run-command.ts'

/** Name of the synthesized deploy root. It is private and never published. */
const CLOSURE_NAME = 'omdsh-runtime-closure'

/** Version of the synthesized deploy root. Nothing reads it; pnpm requires one. */
const CLOSURE_VERSION = '0.0.1'

/**
 * Which dependencies of the closure may run an install script.
 *
 * pnpm 10+ blocks every install and build script until it is reviewed, and the
 * staging root gets no say from this repository's own `pnpm-workspace.yaml` —
 * it is a separate workspace by construction. So the review travels here.
 *
 * Narrower than the desktop workspace's list, because this is the RUNTIME's
 * closure rather than the shell's: `electron` and `esbuild` are the shell's
 * build-time dependencies and never appear here. `node-addon-require-builtin`
 * reaches the closure but is left unlisted, which denies it, exactly as the
 * workspace denies it.
 */
const CLOSURE_ALLOW_BUILDS: Readonly<Record<string, boolean>> = {
  // Restores the executable bit on the macOS spawn helper, which the
  // persistent-terminal tools need in the shipped closure.
  '@deepseek-ai/dsh-subprocess-local': true,
  // JSONL durability calls MoveFileExW with write-through publication on Windows.
  koffi: true,
  // The persistent PTY backend, including ConPTY on Windows.
  'node-pty': true,
  // Pulled in by an optional LLM API backend; its lifecycle scripts are no-ops
  // the runtime does not need.
  '@google/genai': false,
  protobufjs: false,
}

/** What a closure install needs to know. */
export interface InstallRuntimeClosureOptions {
  /** Directory to materialize the closure in. Replaced wholesale. */
  readonly staging: string
  /** The dependency map to install, as the runtime pin records it. */
  readonly dependencies: Readonly<Record<string, string>>
  /** pnpm settings the staged install must carry, when the pin sets any. */
  readonly pnpm?: Readonly<Record<string, unknown>>
  /** Directory the install must never write into or delete: the repository. */
  readonly protect: string
  /** Diagnostic prefix on this step's logs and errors. */
  readonly prefix: string
  /** Report what would happen and change nothing. */
  readonly dryRun: boolean
}

/**
 * The staging root's workspace file.
 *
 * Written as text rather than through a YAML serializer: this repository has no
 * YAML dependency, the document is three fixed keys, and every value in it is
 * either a boolean or a quoted package name.
 * @param allowBuilds - the reviewed build-script decisions.
 * @returns the document.
 */
function workspaceDocument(allowBuilds: Readonly<Record<string, boolean>>): string {
  const entries = Object.entries(allowBuilds)
    .map(([name, allowed]) => `  '${name}': ${String(allowed)}`)
    .join('\n')
  return [
    '# Generated by scripts/runtime-closure.ts. `packages: []` is what makes this',
    '# directory a workspace root of its own, so the install resolves from the',
    '# registry rather than through the desktop workspace above it.',
    'packages: []',
    'allowBuilds:',
    entries,
    '# Every dependency here is pinned to one release this repository chooses',
    "# deliberately, so pnpm's release-age gate has nothing left to protect.",
    'minimumReleaseAge: 0',
    '',
  ].join('\n')
}

/**
 * Refuse a staging directory that would take the repository with it.
 *
 * The install replaces `staging` wholesale, so a path that contains the
 * repository — or is it — turns one packaging run into data loss.
 * @param staging - the directory about to be replaced.
 * @param protect - the directory that must survive.
 * @param prefix - diagnostic prefix.
 * @throws Error when the staging directory is unsafe.
 */
function assertSafeStaging(staging: string, protect: string, prefix: string): void {
  const target = resolve(staging)
  const guarded = resolve(protect)
  if (target === guarded || guarded.startsWith(`${target}${sep}`)) {
    throw new Error(`${prefix}: refusing to stage the closure at ${target}, which contains ${guarded}.`)
  }
}

/**
 * Install the harness closure into the staging directory.
 * @param options - where to put it and what to put there.
 * @returns nothing; the closure is on disk at `options.staging`.
 * @throws Error when the staging directory is unsafe or the install fails.
 */
export async function installRuntimeClosure(options: InstallRuntimeClosureOptions): Promise<void> {
  assertSafeStaging(options.staging, options.protect, options.prefix)

  const manifest = {
    name: CLOSURE_NAME,
    version: CLOSURE_VERSION,
    private: true,
    type: 'module',
    dependencies: options.dependencies,
    ...options.pnpm !== undefined && { pnpm: options.pnpm },
  }

  if (options.dryRun) {
    console.log(`${options.prefix}: would stage the closure at ${options.staging}`)
    for (const [name, range] of Object.entries(options.dependencies)) {
      console.log(`${options.prefix}:   ${name}@${range}`)
    }
    return
  }

  // Replaced rather than updated: a closure carrying a previous run's pruned
  // tree, or a previous target's natives, is not the closure this pin names.
  await rm(options.staging, { recursive: true, force: true })
  await mkdir(options.staging, { recursive: true })
  await writeFile(join(options.staging, 'package.json'), `${JSON.stringify(manifest, undefined, 2)}\n`)
  await writeFile(join(options.staging, 'pnpm-workspace.yaml'), workspaceDocument(CLOSURE_ALLOW_BUILDS))

  await runCommand({
    label: 'deploy the harness closure',
    command: 'pnpm',
    // `--prod` because the closure runs the harness rather than building it,
    // and `--node-linker=hoisted` because the tree is about to be copied into
    // an application bundle, where a symlink into pnpm's store resolves to
    // nothing.
    args: ['install', '--prod', '--node-linker=hoisted'],
    cwd: options.staging,
    prefix: options.prefix,
    dryRun: false,
  })
}
